### ISSUE TITLE
New ObjectFactory Creation

### ISSUE THREAD

**Issue by sephirothkod** [scientist-softserv/west-virginia-university#26]
Somewhat relies on #28 and #29 
We need to create an ObjectFactory that does not rely upon the Hyrax actor stack.
- [ ] Create new ObjectFactory file into WVU code base AcdaFactory as a possible name
- [ ] Set Bulkrax.object_factory in Bulkrax initializer to use our new Object Factory
- [ ] add placeholder method names for methods that have other tickets.  

### Notes
`import_behavior.rb` - creates/calls the object factory

### Methods that may need to be created
methods needed inside ObjectFactory:
- [ ] initialize
- [ ] run!
- [ ] create - creates the work #35 
- [ ] update -  updates the work #36 
- [ ] search_by_id - finds the entry by object id
- [ ] search_by_identifier finds the entry by bulkrax identifier
- [ ] clean_attributes - takes parsed attributes and remove things if we are creating rather than updating)
- [ ] method to call file_creation_service (https://github.com/scientist-softserv/west-virginia-university/issues/27) - Make another ticket for after 27 is completed
