### ISSUE TITLE
As a user, I can access the advanced search functionality via the search page

### ISSUE THREAD

**Issue by jillpe** [scientist-softserv/west-virginia-university#98]
## Summary
related to 
- #92 

## Tasks
- [ ] Add advanced search gem
- [ ] Incorporate advanced search view into UI

## Testing Instructions
- [ ] Click 'More options' near the search bar

**Comment by kirkkwang** [comment]
✅ Pass


![Image](https://github.com/scientist-softserv/west-virginia-university/assets/19597776/6d85bbfc-882d-4a9d-9191-f1aa66aa445d)

**Comment by mmizalmond** [comment]
This is working correctly, thank you!
